### ISSUE TITLE
Changing Tooltip Icon to Text

### ISSUE THREAD

**Issue by seoanalyze** [philperusse/nova-tooltip-field#1]
Hey,
first at all: Thank you for this package!

Is it possible to change the Tooltip icon and replace it with a text? Would be nice if I can choose the Tooltip text within the Tooltip function like this:

Tooltip::make('More', 'Mouse over this text', function(){
    return 'This a tooltip. You can put lengthy content here or any additional info.';
 }),

**Comment by philperusse** [comment]
Hi, 
That could be pretty easy.
Are you willing to submit a PR?

**Comment by philperusse** [comment]
#3
