### ISSUE TITLE
tooltip icon and hover not showing on index

### ISSUE THREAD

**Issue by chorton** [philperusse/nova-tooltip-field#5]
laravel/nova v2.10.1 

The issue:

`Tooltip::make('Roles', function () {
    return 'tooltip message';
})
    ->onlyOnIndex(),`

The tooltip icon is not showing and there's no hover text.

<img width="120" alt="Screen Shot 2020-02-13 at 11 13 22 PM" src="https://user-images.githubusercontent.com/513859/74509569-aeafe980-4eb6-11ea-89af-c042ee47d3af.png">

**Comment by gmedeiros** [comment]
Hey @chorton, I've just installed this package and the same happened to me. I fixed it by running "npm run dev" on the root of the project, have you tried that?

**Comment by chorton** [comment]
That worked!  Thank you, @gmedeiros
